spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1/pineapple?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: pineapple
    password: 123456
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        max-active: 200
        max-wait: 10s
        max-idle: 10
        min-idle: 0
feign:
  okhttp:
    enabled: true
    config:
      connect-timeout: 10s
      read-timeout: 1m
      write-timeout: 2m
      retry-on-connection-failure: true
      pool:
        max-idle-connections: 200
        keep-alive-duration: 5
  client:
    config:
      load:
        # 连接超时时间,单位毫秒
        connectTimeout: 10000
        # 读超时时间,单位毫秒
        readTimeout: 600000
        # 日志级别
        loggerLevel: basic
mybatis-plus:
  mapper-locations:
    - classpath*:mapper/**/*Mapper.xml
    - classpath*:retrieve/**/*Retrieve.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
id:
  snowflake:
    datacenter-id: 2
    machine-id: 1
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%18.18t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    org.pineapple: debug
swagger:
  enabled: true
flow:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://127.0.0.1/pineapple?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
  username: pineapple
  password: 123456
  schema: flow
  db-schema-type: db_schema_update_false
  activity-font-name: 宋体
  label-font-name: 宋体
  annotation-font-name: 宋体