spring:
  servlet:
    multipart:
      # 开启文件上传
      enabled: true
      # 文件最大大小
      max-file-size: 10MB
  cache:
    # 缓存类型 使用redis
    type: redis
    # redis缓存配置
    redis:
      # 不允许缓存null值
      cache-null-values: false
      # 缓存前缀
      key-prefix: pineapple:cache
      # 缓存时效 4个小时
      time-to-live: PT4H
# feign配置
feign:
  okhttp:
    # 开启okhttp
    enabled: true
    config:
      # 连接超时时间 10秒
      connect-timeout: 10s
      # 读取超时时间 1分钟
      read-timeout: 1m
      # 写入超时时间 2分钟
      write-timeout: 2m
      # 连接失败后是否重试
      retry-on-connection-failure: true
      pool:
        # 最大连接数 200
        max-idle-connections: 200
        # 连接存活时间(分钟) 5分钟
        keep-alive-duration: 5
  client:
    config:
      load:
        # 连接超时时间,单位毫秒
        connectTimeout: 10000
        # 读超时时间,单位毫秒
        readTimeout: 600000
        # 日志级别
        loggerLevel: basic