spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: pineapple-system
          uri: lb://pineapple-system
          predicates:
            - Path=/system/**
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        max-active: 200
        max-wait: 10s
        max-idle: 10
        min-idle: 0
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%18.18t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    org.pineapple: debug
swagger:
  enabled: true
pineapple:
  gateway:
    white:
      urls:
        - /security/**
        - "/swagger-resources/**"
        - "/swagger/**"
        - /webjars/**
        - /**/v2/**
        - /**/v3/**
        - /swagger-ui/**
        - /swagger-ui.html/**
        - /doc.html/**
        - /favicon.ico
        - /csrf
        - "/"
        - "/doc.html"
        - "/swagger-resources/**"
        - "/swagger/**"
        - "/*/v2/api-docs"
        - "/*/v3/api-docs"
        - "/*/*.js"
        - "/*/*.css"
        - "/*/*.png"
        - "/*/*.ico"