spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: pineapple-system
          uri: lb://pineapple-system
          predicates:
            - Path=/system/**
        - id: pineapple-auth-center
          uri: lb://pineapple-auth-center
          predicates:
            - Path=/auth/**